In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("raw_data.csv")

#method that apply

In [4]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [5]:
df.describe()

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [10]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='str')

In [12]:
df.head(4)

   id        name   age country   gender   income
0   1    John Doe  29.0     USA     Male  55000.0
1   1    John Doe  29.0     USA     Male  55000.0
2   2  Jane Smith   NaN  Canada   Female  62000.0
3   3        Alex   NaN     USA  Unknown  47000.0

In [13]:
df.tail(3)

    id         name   age country  gender   income
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [16]:
df.sample(1)

   id  name  age country   gender   income
3   3  Alex  NaN     USA  Unknown  47000.0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     str
 2   age      8 non-null      float64
 3   country  10 non-null     str
 4   gender   10 non-null     str
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 849.0 bytes

In [18]:
df.shape

(11, 6)

In [20]:
df.nunique()

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64