In [49]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")

#method that apply

In [3]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df.describe()

              id        age        income
count  11.000000   8.000000     10.000000
mean    5.090909  32.750000  57600.000000
std     3.176619   6.065123   8896.940798
min     1.000000  27.000000  45000.000000
25%     2.500000  29.000000  52000.000000
50%     5.000000  30.000000  56500.000000
75%     7.500000  35.000000  62000.000000
max    10.000000  45.000000  73000.000000

In [10]:
df.columns

Index(['id', 'name', 'age', 'country', 'gender', 'income'], dtype='str')

In [12]:
df.head(4)

   id        name   age country   gender   income
0   1    John Doe  29.0     USA     Male  55000.0
1   1    John Doe  29.0     USA     Male  55000.0
2   2  Jane Smith   NaN  Canada   Female  62000.0
3   3        Alex   NaN     USA  Unknown  47000.0

In [13]:
df.tail(3)

    id         name   age country  gender   income
8    8   Rachel Lee  29.0     USA  Female  62000.0
9    9  Carlos Ruiz   NaN  Mexico    Male  45000.0
10  10  Emily Davis  31.0     USA     NaN  58000.0

In [16]:
df.sample(1)

   id  name  age country   gender   income
3   3  Alex  NaN     USA  Unknown  47000.0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     str
 2   age      8 non-null      float64
 3   country  10 non-null     str
 4   gender   10 non-null     str
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 849.0 bytes

In [18]:
df.shape

(11, 6)

In [7]:
#handling data
df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [8]:
df.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [9]:
df.dropna()

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [10]:
df.fillna(0)

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [28]:
clean_data = df.copy()

In [31]:
mean_val  = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(mean_val)
clean_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [32]:
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [33]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [13]:
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [16]:
df.dtypes

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [32]:
df.columns
df2 = df.copy()
df2["age"] = df2["age"].fillna(0)
df2["age"]
df2["age"] = df2["age"].astype("int64")
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      NaN
5    5        Li Wei   27   China     Male  51000.0
6    6           NaN   45   India   Female  73000.0
7    7    Ahmed Khan   38     NaN     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA      NaN  58000.0

In [37]:
df_1 = pd.read_csv("data_date.csv")

In [38]:
df_1

,Date,Country,Status,AQI Value
0,2022-07-21,Albania,Good,14
1,2022-07-21,Algeria,Moderate,65
2,2022-07-21,Andorra,Moderate,55
3,2022-07-21,Angola,Unhealthy for Sensitive Groups,113
4,2022-07-21,Argentina,Moderate,63
...,...,...,...,...
26661,2026-09-03,United Kingdom of Great Britain and Northern I...,Good,36
26662,2026-09-03,United States of America,Moderate,72
26663,2026-09-03,Uzbekistan,Moderate,98
26664,2026-09-03,Vietnam,Good,27
26665,2026-09-03,Zambia,Unhealthy for Sensitive Groups,148

In [41]:
df_1.dtypes

Date           str
Country        str
Status         str
AQI Value    int64
dtype: object

In [47]:
df_1["Date"]= pd.to_datetime(df_1["Date"])
df_1["Date"].dtypes

dtype('<M8[us]')

In [74]:
#Handling string
df_2 = df.copy()
df_2["name"] = df_2["name"].str.capitalize()
df_2["name"]
df_2["name"] = df_2["name"].str.strip()
df_2["name"]
# df_2["name"] = df_2["name"].str.split()
# df_2["name"]
df_2["name"] = df_2["name"].str.contains("Alex" , case = False , na=False)
df_2["name"]

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: name, dtype: bool