In [2]:
import pandas as pd

In [4]:
df  = pd.read_csv("data_date.csv")

In [5]:
df

,Date,Country,Status,AQI Value
0,2022-07-21,Albania,Good,14
1,2022-07-21,Algeria,Moderate,65
2,2022-07-21,Andorra,Moderate,55
3,2022-07-21,Angola,Unhealthy for Sensitive Groups,113
4,2022-07-21,Argentina,Moderate,63
...,...,...,...,...
26661,2026-09-03,United Kingdom of Great Britain and Northern I...,Good,36
26662,2026-09-03,United States of America,Moderate,72
26663,2026-09-03,Uzbekistan,Moderate,98
26664,2026-09-03,Vietnam,Good,27
26665,2026-09-03,Zambia,Unhealthy for Sensitive Groups,148

In [7]:
df.describe()

          AQI Value
count  26666.000000
mean      62.629341
std       50.176347
min        1.000000
25%       29.000000
50%       52.000000
75%       81.000000
max      963.000000

In [8]:
df.sample(1)

            Date Country Status  AQI Value
2726  2022-08-04  Gambia   Good         25

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26666 entries, 0 to 26665
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       26666 non-null  str
 1   Country    26666 non-null  str
 2   Status     26666 non-null  str
 3   AQI Value  26666 non-null  int64
dtypes: int64(1), str(3)
memory usage: 1.5 MB

In [10]:
df.nunique()

Date         202
Country      142
Status         6
AQI Value    378
dtype: int64

In [11]:
df.shape

(26666, 4)

In [15]:
df.columns

Index(['Date', 'Country', 'Status', 'AQI Value'], dtype='str')

In [17]:
#indexing and selecting 
df['AQI Value']

0         14
1         65
2         55
3        113
4         63
        ...
26661     36
26662     72
26663     98
26664     27
26665    148
Name: AQI Value, Length: 26666, dtype: int64

In [18]:
df.loc[1]

Date         2022-07-21
Country         Algeria
Status         Moderate
AQI Value            65
Name: 1, dtype: object

In [19]:
df.loc[0:2]

         Date  Country    Status  AQI Value
0  2022-07-21  Albania      Good         14
1  2022-07-21  Algeria  Moderate         65
2  2022-07-21  Andorra  Moderate         55

In [20]:
df.iloc[0:3]

         Date  Country    Status  AQI Value
0  2022-07-21  Albania      Good         14
1  2022-07-21  Algeria  Moderate         65
2  2022-07-21  Andorra  Moderate         55

In [24]:
df.iloc[0:3 , 0:2]

         Date  Country
0  2022-07-21  Albania
1  2022-07-21  Algeria
2  2022-07-21  Andorra

In [26]:
df.loc[0:7 , ['Date', 'Country', 'Status']]

         Date    Country                          Status
0  2022-07-21    Albania                            Good
1  2022-07-21    Algeria                        Moderate
2  2022-07-21    Andorra                        Moderate
3  2022-07-21     Angola  Unhealthy for Sensitive Groups
4  2022-07-21  Argentina                        Moderate
5  2022-07-21    Armenia                        Moderate
6  2022-07-21  Australia                        Moderate
7  2022-07-21    Austria                            Good

In [32]:
df.iat[0 ,2]

'Good'

In [33]:
city = df['Date'].copy()

In [34]:
city[0] = "mumbai"

In [37]:
city

0            mumbai
1        2022-07-21
2        2022-07-21
3        2022-07-21
4        2022-07-21
            ...
26661    2026-09-03
26662    2026-09-03
26663    2026-09-03
26664    2026-09-03
26665    2026-09-03
Name: Date, Length: 26666, dtype: str

In [43]:
df.columns

Index(['Date', 'Country', 'Status', 'AQI Value'], dtype='str')

In [56]:
df.query("`AQI Value`> 100")

,Date,Country,Status,AQI Value
3,2022-07-21,Angola,Unhealthy for Sensitive Groups,113
9,2022-07-21,Bahrain,Unhealthy,165
10,2022-07-21,Bangladesh,Unhealthy for Sensitive Groups,141
20,2022-07-21,Burkina Faso,Unhealthy for Sensitive Groups,118
25,2022-07-21,Central African Republic,Unhealthy,156
...,...,...,...,...
26647,2026-09-03,South Africa,Unhealthy for Sensitive Groups,134
26654,2026-09-03,Tajikistan,Unhealthy for Sensitive Groups,121
26658,2026-09-03,Uganda,Unhealthy for Sensitive Groups,119
26660,2026-09-03,United Arab Emirates,Unhealthy for Sensitive Groups,117
26665,2026-09-03,Zambia,Unhealthy for Sensitive Groups,148

In [58]:
df[df["AQI Value"]>100]

,Date,Country,Status,AQI Value
3,2022-07-21,Angola,Unhealthy for Sensitive Groups,113
9,2022-07-21,Bahrain,Unhealthy,165
10,2022-07-21,Bangladesh,Unhealthy for Sensitive Groups,141
20,2022-07-21,Burkina Faso,Unhealthy for Sensitive Groups,118
25,2022-07-21,Central African Republic,Unhealthy,156
...,...,...,...,...
26647,2026-09-03,South Africa,Unhealthy for Sensitive Groups,134
26654,2026-09-03,Tajikistan,Unhealthy for Sensitive Groups,121
26658,2026-09-03,Uganda,Unhealthy for Sensitive Groups,119
26660,2026-09-03,United Arab Emirates,Unhealthy for Sensitive Groups,117
26665,2026-09-03,Zambia,Unhealthy for Sensitive Groups,148

In [65]:
copy = df.query("`AQI Value` > 100")[["Country","Status"]].copy()
copy

                        Country                          Status
3                        Angola  Unhealthy for Sensitive Groups
9                       Bahrain                       Unhealthy
10                   Bangladesh  Unhealthy for Sensitive Groups
20                 Burkina Faso  Unhealthy for Sensitive Groups
25     Central African Republic                       Unhealthy
...                         ...                             ...
26647              South Africa  Unhealthy for Sensitive Groups
26654                Tajikistan  Unhealthy for Sensitive Groups
26658                    Uganda  Unhealthy for Sensitive Groups
26660      United Arab Emirates  Unhealthy for Sensitive Groups
26665                    Zambia  Unhealthy for Sensitive Groups

[4223 rows x 2 columns]