In [1]:
import pandas as pd

In [42]:
df = pd.read_csv("Salary.csv")
df

    YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872
30             11.2  127345
31             11.5  126756
32             12.3  128765
33             12.9  135675
34             13.5  139465

In [43]:
df2 = df.copy()
df2.columns

Index(['YearsExperience', 'Salary'], dtype='str')

In [44]:
df2["YearsExperience"] = df2["YearsExperience"].apply(lambda x:"20% increment" if x >= 5  else "freshers")

In [45]:
df2

   YearsExperience  Salary
0         freshers   39343
1         freshers   46205
2         freshers   37731
3         freshers   43525
4         freshers   39891
5         freshers   56642
6         freshers   60150
7         freshers   54445
8         freshers   64445
9         freshers   57189
10        freshers   63218
11        freshers   55794
12        freshers   56957
13        freshers   57081
14        freshers   61111
15        freshers   67938
16   20% increment   66029
17   20% increment   83088
18   20% increment   81363
19   20% increment   93940
20   20% increment   91738
21   20% increment   98273
22   20% increment  101302
23   20% increment  113812
24   20% increment  109431
25   20% increment  105582
26   20% increment  116969
27   20% increment  112635
28   20% increment  122391
29   20% increment  121872
30   20% increment  127345
31   20% increment  126756
32   20% increment  128765
33   20% increment  135675
34   20% increment  139465

In [46]:
maping = { "freshers" : "New in job " , "20% increment" : "experience" }
df2["YearsExperience"] = df2["YearsExperience"].map(maping)
df2

   YearsExperience  Salary
0      New in job    39343
1      New in job    46205
2      New in job    37731
3      New in job    43525
4      New in job    39891
5      New in job    56642
6      New in job    60150
7      New in job    54445
8      New in job    64445
9      New in job    57189
10     New in job    63218
11     New in job    55794
12     New in job    56957
13     New in job    57081
14     New in job    61111
15     New in job    67938
16      experience   66029
17      experience   83088
18      experience   81363
19      experience   93940
20      experience   91738
21      experience   98273
22      experience  101302
23      experience  113812
24      experience  109431
25      experience  105582
26      experience  116969
27      experience  112635
28      experience  122391
29      experience  121872
30      experience  127345
31      experience  126756
32      experience  128765
33      experience  135675
34      experience  139465

In [49]:
df2 = df2.assign(year = df2["YearsExperience"])
df2

   YearsExperience  Salary         year
0      New in job    39343  New in job
1      New in job    46205  New in job
2      New in job    37731  New in job
3      New in job    43525  New in job
4      New in job    39891  New in job
5      New in job    56642  New in job
6      New in job    60150  New in job
7      New in job    54445  New in job
8      New in job    64445  New in job
9      New in job    57189  New in job
10     New in job    63218  New in job
11     New in job    55794  New in job
12     New in job    56957  New in job
13     New in job    57081  New in job
14     New in job    61111  New in job
15     New in job    67938  New in job
16      experience   66029   experience
17      experience   83088   experience
18      experience   81363   experience
19      experience   93940   experience
20      experience   91738   experience
21      experience   98273   experience
22      experience  101302   experience
23      experience  113812   experience
24      experience  109431   experience
25      experience  105582   experience
26      experience  116969   experience
27      experience  112635   experience
28      experience  122391   experience
29      experience  121872   experience
30      experience  127345   experience
31      experience  126756   experience
32      experience  128765   experience
33      experience  135675   experience
34      experience  139465   experience

In [55]:
df2["year"] = df2["year"].replace(["New in job ", "experience"],[1,2])
df2

   YearsExperience  Salary year
0      New in job    39343    1
1      New in job    46205    1
2      New in job    37731    1
3      New in job    43525    1
4      New in job    39891    1
5      New in job    56642    1
6      New in job    60150    1
7      New in job    54445    1
8      New in job    64445    1
9      New in job    57189    1
10     New in job    63218    1
11     New in job    55794    1
12     New in job    56957    1
13     New in job    57081    1
14     New in job    61111    1
15     New in job    67938    1
16      experience   66029    2
17      experience   83088    2
18      experience   81363    2
19      experience   93940    2
20      experience   91738    2
21      experience   98273    2
22      experience  101302    2
23      experience  113812    2
24      experience  109431    2
25      experience  105582    2
26      experience  116969    2
27      experience  112635    2
28      experience  122391    2
29      experience  121872    2
30      experience  127345    2
31      experience  126756    2
32      experience  128765    2
33      experience  135675    2
34      experience  139465    2

In [62]:
df2 = df2.sort_values(by= "Salary")
df2

   YearsExperience  Salary year
2      New in job    37731    1
0      New in job    39343    1
4      New in job    39891    1
3      New in job    43525    1
1      New in job    46205    1
7      New in job    54445    1
11     New in job    55794    1
5      New in job    56642    1
12     New in job    56957    1
13     New in job    57081    1
9      New in job    57189    1
6      New in job    60150    1
14     New in job    61111    1
10     New in job    63218    1
8      New in job    64445    1
16      experience   66029    2
15     New in job    67938    1
18      experience   81363    2
17      experience   83088    2
20      experience   91738    2
19      experience   93940    2
21      experience   98273    2
22      experience  101302    2
25      experience  105582    2
24      experience  109431    2
27      experience  112635    2
23      experience  113812    2
26      experience  116969    2
29      experience  121872    2
28      experience  122391    2
31      experience  126756    2
30      experience  127345    2
32      experience  128765    2
33      experience  135675    2
34      experience  139465    2

In [64]:
sorted_df = df2.sort_values(by = "Salary" , ascending = False)

In [65]:
sorted_df

   YearsExperience  Salary year
34      experience  139465    2
33      experience  135675    2
32      experience  128765    2
30      experience  127345    2
31      experience  126756    2
28      experience  122391    2
29      experience  121872    2
26      experience  116969    2
23      experience  113812    2
27      experience  112635    2
24      experience  109431    2
25      experience  105582    2
22      experience  101302    2
21      experience   98273    2
19      experience   93940    2
20      experience   91738    2
17      experience   83088    2
18      experience   81363    2
15     New in job    67938    1
16      experience   66029    2
8      New in job    64445    1
10     New in job    63218    1
14     New in job    61111    1
6      New in job    60150    1
9      New in job    57189    1
13     New in job    57081    1
12     New in job    56957    1
5      New in job    56642    1
11     New in job    55794    1
7      New in job    54445    1
1      New in job    46205    1
3      New in job    43525    1
4      New in job    39891    1
0      New in job    39343    1
2      New in job    37731    1

In [68]:
a_df = sorted_df.reset_index(drop = True)
a_df

   YearsExperience  Salary year
0       experience  139465    2
1       experience  135675    2
2       experience  128765    2
3       experience  127345    2
4       experience  126756    2
5       experience  122391    2
6       experience  121872    2
7       experience  116969    2
8       experience  113812    2
9       experience  112635    2
10      experience  109431    2
11      experience  105582    2
12      experience  101302    2
13      experience   98273    2
14      experience   93940    2
15      experience   91738    2
16      experience   83088    2
17      experience   81363    2
18     New in job    67938    1
19      experience   66029    2
20     New in job    64445    1
21     New in job    63218    1
22     New in job    61111    1
23     New in job    60150    1
24     New in job    57189    1
25     New in job    57081    1
26     New in job    56957    1
27     New in job    56642    1
28     New in job    55794    1
29     New in job    54445    1
30     New in job    46205    1
31     New in job    43525    1
32     New in job    39891    1
33     New in job    39343    1
34     New in job    37731    1

In [71]:
a_df["ranking"] = a_df["Salary"].rank()
a_df.sort_values(by = "ranking")

   YearsExperience  Salary year  ranking
34     New in job    37731    1      1.0
33     New in job    39343    1      2.0
32     New in job    39891    1      3.0
31     New in job    43525    1      4.0
30     New in job    46205    1      5.0
29     New in job    54445    1      6.0
28     New in job    55794    1      7.0
27     New in job    56642    1      8.0
26     New in job    56957    1      9.0
25     New in job    57081    1     10.0
24     New in job    57189    1     11.0
23     New in job    60150    1     12.0
22     New in job    61111    1     13.0
21     New in job    63218    1     14.0
20     New in job    64445    1     15.0
19      experience   66029    2     16.0
18     New in job    67938    1     17.0
17      experience   81363    2     18.0
16      experience   83088    2     19.0
15      experience   91738    2     20.0
14      experience   93940    2     21.0
13      experience   98273    2     22.0
12      experience  101302    2     23.0
11      experience  105582    2     24.0
10      experience  109431    2     25.0
9       experience  112635    2     26.0
8       experience  113812    2     27.0
7       experience  116969    2     28.0
6       experience  121872    2     29.0
5       experience  122391    2     30.0
4       experience  126756    2     31.0
3       experience  127345    2     32.0
2       experience  128765    2     33.0
1       experience  135675    2     34.0
0       experience  139465    2     35.0